# Generated by Django 2.1.3 on 2018-11-05 12:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'db_table': 'customer',
                'ordering': ['-last_name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(30)])),
                ('customer_address', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_order', to='ordering.Customer')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Pizzas',
                'db_table': 'pizza',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_order', to='ordering.Pizza'),
        ),
    ]
